name = "ship-log-search"
compatibility_date = "2026-07-17"
main = "src/index.js"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "ship-log"

[[d1_databases]]
binding = "DB"
database_name = "ship-log-db"
database_id = "98eae8b5-6b7e-4d16-b70f-a0d05e5f6c58"
